#!/bin/bash
resolution=$(xrandr | grep '*' | awk '{print $1}')

if pstree|grep -i cage &>/dev/null; then
	timeout 5s killall -9 cage -w &> /dev/null
fi

if waydroid status|grep -i running &>/dev/null; then
	sudo waydroid-container-stop
fi

sudo waydroid-container-start

cage -- bash -c "wlr-randr --output X11-1 --custom-mode ${resolution}@60Hz & waydroid show-full-ui & sleep 10 & sudo waydroid-fix-storage" &

sleep 5
tail --pid=$(pidof -w lmkd) -f /dev/null 1>&2

if [[ "$?" == "0" ]]; then
        if pstree|grep -i cage &>/dev/null; then
                timeout 5s killall -9 cage -w &>/dev/null
        fi

        sudo waydroid-container-stop
fi
