#!/bin/bash
resolution=$(xrandr | grep '*' | awk '{print $1}')

if pstree|grep -i cage &>/dev/null; then
	timeout 5s killall -9 cage -w &> /dev/null
fi

if waydroid status|grep -i running &>/dev/null; then
	sudo waydroid-container-stop
fi

if ! grep -i redfin /var/lib/waydroid/waydroid_base.prop &>/dev/null; then # upgraded or freshly installed
	# change GPU rendering to use minigbm_gbm_mesa
	sudo sed -i "s/ro.hardware.gralloc=.*/ro.hardware.gralloc=minigbm_gbm_mesa/g" /var/lib/waydroid/waydroid_base.prop

	sudo tee -a /var/lib/waydroid/waydroid_base.prop > /dev/null <<'EOF'

##########################################################################
# controller config for udev events
persist.waydroid.udev=true
persist.waydroid.uevent=true

# disable root
ro.adb.secure=1
ro.debuggable=0
ro.build.selinux=1

##########################################################################
### start of custom build prop - you can safely delete if this causes issue

ro.product.brand=google
ro.product.manufacturer=Google
ro.system.build.product=redfin
ro.product.name=redfin
ro.product.device=redfin
ro.product.model=Pixel 5
ro.system.build.flavor=redfin-user
ro.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
ro.system.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
ro.bootimage.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
ro.build.display.id=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
ro.build.tags=release-keys
ro.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
ro.vendor.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
ro.vendor.build.id=RQ3A.211001.001
ro.vendor.build.tags=release-keys
ro.vendor.build.type=user
ro.odm.build.tags=release-keys

### end of custom build prop - you can safely delete if this causes issue
##########################################################################
EOF
fi

sudo waydroid-container-start

cage -- bash -c "wlr-randr --output X11-1 --custom-mode ${resolution}@60Hz & waydroid show-full-ui & sudo waydroid-startup-script" &

sleep 5
tail --pid=$(pidof -w lmkd) -f /dev/null 1>&2

if [[ "$?" == "0" ]]; then
	if pstree|grep -i cage &>/dev/null; then
		timeout 5s killall -9 cage -w &>/dev/null
	fi

	sudo waydroid-container-stop
fi

exit 0
