#!/bin/bash
resolution=$(xrandr | grep '*' | awk '{print $1}')

if pstree|grep -i cage; then
        timeout 5s killall -2 cage -w &> /dev/null

        if [ $? -eq 124 ]; then
                # Timed out, this will shut it down for good using SIGKILL
                timeout 5s killall -9 cage -w &> /dev/null
        fi
fi

if waydroid status|grep -i running; then
	sudo waydroid-container-stop
fi

sudo waydroid-container-start

cage -- bash -c "wlr-randr --output X11-1 --custom-mode ${resolution}@60Hz; waydroid show-full-ui \$@ & sleep 5; sudo waydroid-fix-storage"

# Reset cage so it doesn't nuke the display environment variable
cage -- bash -c 'wlr-randr'
