#!/bin/bash
sudo systemctl start waydroid-container

if [[ ! -L /dev/anbox-binder ]] || ! readlink -q /dev/anbox-binder &>/dev/null; then
	sleep 5
	rm /dev/anbox-binder &>/dev/null
	ln -s /dev/binderfs/binder /dev/anbox-binder &>/dev/null
	chmod o=rw /dev/anbox-binder
fi
