#!/bin/bash
PASSWORD=$(zenity --password --title "sudo Password Authentication")
echo -e "$PASSWORD\n" | sudo -S ls &> /dev/null

if [ $? -ne 0 ]; then
	echo "sudo password is wrong!" | zenity --text-info --title "Waydroid Toolbox" --width 400 --height 200
	exit 1
fi

while true; do
	Choice=$(zenity --width 850 --height 600 --list --radiolist --multiple --title "Waydroid Toolbox for SteamOS Waydroid script - https://github.com/ryanrudolfoba/steamos-waydroid-installer"\
	--column "Select One" \
	--column "Option" \
	--column="Description"\
	FALSE ADBLOCK "Disable or download/update the custom adblock hosts file."\
	FALSE AUDIO "Enable or disable the custom audio fixes."\
	FALSE GPU "Change the GPU config - GBM or MINIGBM."\
	FALSE VMSZ "Change Android vm size (container must be running)."\
	FALSE UNINSTALL "Choose this to uninstall Waydroid and revert any changes made."\
	TRUE EXIT "Exit the Waydroid Toolbox")

	if [ $? -eq 1 ] || [[ "$Choice" == "EXIT" ]]; then
		echo User pressed CANCEL / EXIT.
		exit 0

	elif [[ "$Choice" == "ADBLOCK" ]]; then
		ADBLOCK_Choice=$(zenity --width 600 --height 600 --list --radiolist --multiple --title "Waydroid Toolbox" --column "Select One" --column "Option" --column "Description"\
		FALSE DISABLE "Disable the custom adblock hosts file."\
		FALSE UPDATE "Update and enable the custom adblock hosts file."\
		TRUE MENU "Waydroid Toolbox Main Menu")

		if [ $? -eq 1 ] || [[ "$ADBLOCK_Choice" == "MENU" ]]; then
			echo User pressed CANCEL. Going back to main menu.

		elif [[ "$ADBLOCK_Choice" == "DISABLE" ]]; then
			# Disable the custom adblock hosts file
			echo -e "$PASSWORD\n" | sudo -S rm /var/lib/waydroid/overlay/system/etc/hosts &> /dev/null

			zenity --warning --title "Waydroid Toolbox" --text "Custom adblock hosts file has been disabled!" --width 350 --height 75

		elif [[ "$ADBLOCK_Choice" == "UPDATE" ]]; then
			# get the latest custom adblock hosts file from steven black github
			echo -e "$PASSWORD\n" | sudo -S wget https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts -O /var/lib/waydroid/overlay/system/etc/hosts

			zenity --warning --title "Waydroid Toolbox" --text "Custom adblock hosts file has been updated!" --width 350 --height 75
		fi
	elif [[ "$Choice" == "GPU" ]]; then
		GPU_Choice=$(zenity --width 600 --height 600 --list --radiolist --multiple --title "Waydroid Toolbox" --column "Select One" --column "Option" --column "Description"\
		FALSE GBM "Use gbm config for GPU."\
		FALSE MINIGBM "Use minigbm_gbm_mesa for GPU (default)."\
		TRUE MENU "Waydroid Toolbox Main Menu")

		if [ $? -eq 1 ] || [[ "$GPU_Choice" == "MENU" ]]; then
			echo User pressed CANCEL. Going back to main menu.

		elif [[ "$GPU_Choice" == "GBM" ]]; then
			# Edit waydroid prop file to use gbm
			echo -e "$PASSWORD\n" | sudo -S sed -i "s/ro.hardware.gralloc=.*/ro.hardware.gralloc=gbm/g" /var/lib/waydroid/waydroid_base.prop

			zenity --warning --title "Waydroid Toolbox" --text "gbm is now in use!" --width 350 --height 75

		elif [[ "$GPU_Choice" == "MINIGBM" ]]; then
			# Edit waydroid prop file to use minigbm_gbm_mesa
			echo -e "$PASSWORD\n" | sudo -S sed -i "s/ro.hardware.gralloc=.*/ro.hardware.gralloc=minigbm_gbm_mesa/g" /var/lib/waydroid/waydroid_base.prop

			zenity --warning --title "Waydroid Toolbox" --text "minigbm_gbm_mesa is now in use!" --width 350 --height 75
		fi
	elif [[ "$Choice" == "AUDIO" ]]; then
		AUDIO_Choice=$(zenity --width 600 --height 600 --list --radiolist --multiple --title "Waydroid Toolbox" --column "Select One" --column "Option" --column "Description"\
		FALSE DISABLE "Disable the custom audio config."\
		FALSE ENABLE "Enable the custom audio config to lower audio latency."\
		TRUE MENU "Waydroid Toolbox Main Menu")

		if [ $? -eq 1 ] || [[ "$AUDIO_Choice" == "MENU" ]]; then
			echo User pressed CANCEL. Going back to main menu.

		elif [[ "$AUDIO_Choice" == "DISABLE" ]]; then
			# Disable the custom audio config
			echo -e "$PASSWORD\n" | sudo -S mv /var/lib/waydroid/overlay/system/etc/init/audio.rc /var/lib/waydroid/overlay/system/etc/init/audio.rc.disable &> /dev/null

			zenity --warning --title "Waydroid Toolbox" --text "Custom audio config has been disabled!" --width 350 --height 75

		elif [[ "$AUDIO_Choice" == "ENABLE" ]]; then
			# Enable the custom audio config
			echo -e "$PASSWORD\n" | sudo -S mv /var/lib/waydroid/overlay/system/etc/init/audio.rc.disable /var/lib/waydroid/overlay/system/etc/init/audio.rc &> /dev/null

			zenity --warning --title "Waydroid Toolbox" --text "Custom audio config has been enabled!" --width 350 --height 75
		fi
	elif [[ "$Choice" == "VMSZ" ]]; then
		VMSZ_Choice=$(zenity --width 600 --height 600 --list --radiolist --multiple --title "Waydroid Toolbox" --column "Select One" --column "Option" --column "Description"\
		FALSE DEFAULT "Waydroid default"\
		FALSE 720 "720p"\
		FALSE 800 "800p"\
		FALSE 1080 "1080p"\
		TRUE MENU "Waydroid Toolbox Main Menu")

		if [ $? -eq 1 ] || [[ "$VMSZ_Choice" == "MENU" ]]; then
			echo User pressed CANCEL. Going back to main menu.

		elif [[ "$VMSZ_Choice" == "DEFAULT" ]]; then
			waydroid prop set persist.waydroid.height 768
			waydroid prop set persist.waydroid.width 1024

		elif [[ "$VMSZ_Choice" == "720" ]]; then
			waydroid prop set persist.waydroid.height 720
			waydroid prop set persist.waydroid.width 1280

		elif [[ "$VMSZ_Choice" == "800" ]]; then
			waydroid prop set persist.waydroid.height 800
			waydroid prop set persist.waydroid.width 1280

		elif [[ "$VMSZ_Choice" == "1080" ]]; then
			waydroid prop set persist.waydroid.height 1080
			waydroid prop set persist.waydroid.width 1920
		fi
	elif [[ "$Choice" == "UNINSTALL" ]]; then
		UNINSTALL_Choice=$(zenity --width 600 --height 220 --list --radiolist --multiple --title "Waydroid Toolbox" --column "Select One" --column "Option" --column="Description"\
		FALSE WAYDROID "Uninstall Waydroid but keep the Android user data."\
		FALSE FULL "Uninstall Waydroid and delete the Android user data."\
		TRUE MENU "Waydroid Toolbox Main Menu")

		if [ $? -eq 1 ] || [[ "$UNINSTALL_Choice" == "MENU" ]]; then
			echo User pressed CANCEL. Going back to main menu.

		elif [[ "$UNINSTALL_Choice" == "WAYDROID" ]]; then
			echo -e "$PASSWORD\n" | sudo -S systemctl stop waydroid-container
			echo -e "$PASSWORD\n" | sudo -S pacman -R --noconfirm libglibutil libgbinder python-gbinder waydroid wlroots lxc cage wlr-randr
			echo -e "$PASSWORD\n" | sudo -S rm -rf /var/lib/waydroid
			echo -e "$PASSWORD\n" | sudo -S rm /etc/sudoers.d/waydroid-cmds
			echo -e "$PASSWORD\n" | sudo -S firewall-cmd --zone=trusted --remove-interface=waydroid0 &> /dev/null
			echo -e "$PASSWORD\n" | sudo -S firewall-cmd --zone=trusted --remove-port=53/udp &> /dev/null
			echo -e "$PASSWORD\n" | sudo -S firewall-cmd --zone=trusted --remove-port=67/udp &> /dev/null
			echo -e "$PASSWORD\n" | sudo -S firewall-cmd --zone=trusted --remove-forward &> /dev/null
			echo -e "$PASSWORD\n" | sudo -S firewall-cmd --runtime-to-permanent &> /dev/null

			zenity --warning --title "Waydroid Toolbox" --text "Waydroid has been uninstalled! You can now uninstall android-waydroid-cage pkg!" --width 600 --height 75
			exit 0

		elif [[ "$UNINSTALL_Choice" == "FULL" ]]; then
			echo -e "$PASSWORD\n" | sudo -S systemctl stop waydroid-container
			echo -e "$PASSWORD\n" | sudo -S pacman -R --noconfirm libglibutil libgbinder python-gbinder waydroid wlroots lxc cage wlr-randr
			echo -e "$PASSWORD\n" | sudo -S rm -rf /var/lib/waydroid ~/.local/share/waydroid
			echo -e "$PASSWORD\n" | sudo -S rm /etc/sudoers.d/waydroid-cmds
			echo -e "$PASSWORD\n" | sudo -S firewall-cmd --zone=trusted --remove-interface=waydroid0 &> /dev/null
			echo -e "$PASSWORD\n" | sudo -S firewall-cmd --zone=trusted --remove-port=53/udp &> /dev/null
			echo -e "$PASSWORD\n" | sudo -S firewall-cmd --zone=trusted --remove-port=67/udp &> /dev/null
			echo -e "$PASSWORD\n" | sudo -S firewall-cmd --zone=trusted --remove-forward &> /dev/null
			echo -e "$PASSWORD\n" | sudo -S firewall-cmd --runtime-to-permanent &> /dev/null

			zenity --warning --title "Waydroid Toolbox" --text "Waydroid has been uninstalled! You can now uninstall android-waydroid-cage pkg!" --width 600 --height 75
			exit 0
		fi
	fi
done
